apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: auth-app
  name: auth-app
spec:
  selector:
    io.kompose.service: auth-app
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8001
  type: LoadBalancer

