apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: cart-app
  name: cart-app
spec:
  selector:
    io.kompose.service: cart-app
  ports:
    - protocol: TCP
      port: 8013
      targetPort: 8003
  type: LoadBalancer

