apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: orders-app
  name: orders-app
spec:
  selector:
    io.kompose.service: orders-app
  ports:
    - protocol: TCP
      port: 8014
      targetPort: 8004
  type: LoadBalancer

