apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: products-app
  name: products-app
spec:
  selector:
    io.kompose.service: products-app
  ports:
    - protocol: TCP
      port: 8012
      targetPort: 8002
  type: LoadBalancer

