apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: "1.33.0 (3ce457399)"
  labels:
    io.kompose.service: store
  name: store
spec:
  replicas: 5
  selector:
    matchLabels:
      io.kompose.service: store
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: "1.33.0 (3ce457399)"
      labels:
        io.kompose.network/micro-default: "true"
        io.kompose.service: store
    spec:
      containers:
        - name: store
          image: akreem/micro_store:v1.7
          command: ["bash", "-c"]
          args: ["python ./manage.py makemigrations && python ./manage.py migrate && python ./manage.py runserver 0.0.0.0:8000"]
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
