apiVersion: v1
kind: Service
metadata:
  name: store-service
  labels:
    io.kompose.service: store
spec:
  selector:
    io.kompose.service: store
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
